LINODE_IP=192.46.230.221
DB_NAME=argus
DB_USER=deployer
DOCKER_HUB_USERNAME=tankwanghow
IMAGE_NAME=argus
DOCKER_CONTAINER_NAME=argus-app
DOMAIN_NAME=argus.asia
PORT=8083
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=argus.my.asia@gmail.com
MAIL_FROM=argus.my.asia@gmail.com

